# ruff: noqa: E402,I001
import json
import re
import sys
from pathlib import Path
from typing import Any

if __package__ in {None, ""}:
    backend_root = Path(__file__).resolve().parents[1]
    if str(backend_root) not in sys.path:
        sys.path.insert(0, str(backend_root))

from main import create_app


ROOT = Path(__file__).resolve().parents[2]
OPENAPI_PATH = ROOT / "frontend" / "src" / "generated" / "openapi.json"
CONTRACT_PATH = ROOT / "frontend" / "src" / "generated" / "api-contract.ts"
HTTP_METHODS = {"get", "post", "put", "patch", "delete"}


def main() -> None:
    schema = create_app().openapi()
    OPENAPI_PATH.parent.mkdir(parents=True, exist_ok=True)
    OPENAPI_PATH.write_text(
        json.dumps(schema, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    CONTRACT_PATH.write_text(_contract_source(schema), encoding="utf-8")
    print(json.dumps({"openapi": str(OPENAPI_PATH), "contract": str(CONTRACT_PATH)}))


def _contract_source(schema: dict[str, Any]) -> str:
    operations: list[dict[str, Any]] = []
    operation_types: list[tuple[str, str, str]] = []
    for path, methods in sorted(schema.get("paths", {}).items()):
        if not isinstance(methods, dict):
            continue
        for method, definition in sorted(methods.items()):
            if method not in HTTP_METHODS or not isinstance(definition, dict):
                continue
            operation_id = str(definition.get("operationId", ""))
            operations.append(
                {
                    "method": method.upper(),
                    "path": path,
                    "operationId": operation_id,
                }
            )
            if operation_id:
                operation_types.append(
                    (
                        operation_id,
                        _request_body_type(definition),
                        _success_response_type(definition),
                    )
                )

    path_union = _literal_union(sorted({item["path"] for item in operations}))
    method_union = _literal_union(sorted({item["method"] for item in operations}))
    operation_union = _literal_union(
        sorted(item["operationId"] for item in operations if item["operationId"])
    )
    body = json.dumps(operations, ensure_ascii=False, indent=2)
    body = re.sub(r'"([^"]+)":', r"\1:", body)
    component_schemas = schema.get("components", {}).get("schemas", {})
    schema_lines = [
        f"  {json.dumps(name, ensure_ascii=False)}: {_schema_to_typescript(definition)};"
        for name, definition in sorted(component_schemas.items())
        if isinstance(definition, dict)
    ]
    operation_lines = [
        (
            f"  {json.dumps(operation_id, ensure_ascii=False)}: "
            f"{{ requestBody: {request_type}; response: {response_type} }};"
        )
        for operation_id, request_type, response_type in sorted(operation_types)
    ]
    return (
        "/* This file is generated by backend/scripts/export_openapi.py. */\n"
        "/* eslint-disable */\n\n"
        f"export type ApiPath = {path_union};\n"
        f"export type ApiMethod = {method_union};\n"
        f"export type ApiOperationId = {operation_union};\n\n"
        "export type ApiSchemas = {\n"
        + "\n".join(schema_lines)
        + "\n};\n\n"
        + "export type ApiOperations = {\n"
        + "\n".join(operation_lines)
        + "\n};\n\n"
        + "export type ApiOperationRequestBody<T extends keyof ApiOperations> = "
        "ApiOperations[T][\"requestBody\"];\n"
        + "export type ApiOperationResponse<T extends keyof ApiOperations> = "
        "ApiOperations[T][\"response\"];\n\n"
        f"export const apiContract = {body} as const;\n"
    )


def _literal_union(values: list[str]) -> str:
    if not values:
        return "never"
    return " | ".join(json.dumps(value, ensure_ascii=False) for value in values)


def _request_body_type(operation: dict[str, Any]) -> str:
    request_body = operation.get("requestBody")
    if not isinstance(request_body, dict):
        return "never"
    return _content_schema_type(request_body.get("content"), fallback="unknown")


def _success_response_type(operation: dict[str, Any]) -> str:
    responses = operation.get("responses")
    if not isinstance(responses, dict):
        return "void"
    success_codes = sorted(
        str(code)
        for code in responses
        if str(code).startswith("2")
    )
    if not success_codes:
        return "void"
    response = responses.get(success_codes[0])
    if not isinstance(response, dict):
        return "void"
    return _content_schema_type(response.get("content"), fallback="void")


def _content_schema_type(content: Any, *, fallback: str) -> str:
    if not isinstance(content, dict):
        return fallback
    for media_type in ("application/json", "multipart/form-data"):
        media = content.get(media_type)
        if isinstance(media, dict) and isinstance(media.get("schema"), dict):
            return _schema_to_typescript(media["schema"])
    for media in content.values():
        if isinstance(media, dict) and isinstance(media.get("schema"), dict):
            return _schema_to_typescript(media["schema"])
    return fallback


def _schema_to_typescript(schema: dict[str, Any]) -> str:
    reference = schema.get("$ref")
    if isinstance(reference, str):
        return f'ApiSchemas[{json.dumps(reference.rsplit("/", 1)[-1], ensure_ascii=False)}]'

    if "const" in schema:
        return json.dumps(schema["const"], ensure_ascii=False)
    enum_values = schema.get("enum")
    if isinstance(enum_values, list) and enum_values:
        return " | ".join(json.dumps(value, ensure_ascii=False) for value in enum_values)

    for keyword, separator in (("allOf", " & "), ("anyOf", " | "), ("oneOf", " | ")):
        members = schema.get(keyword)
        if isinstance(members, list) and members:
            value = separator.join(
                _schema_to_typescript(member)
                for member in members
                if isinstance(member, dict)
            )
            return f"({value})"

    schema_type = schema.get("type")
    if isinstance(schema_type, list):
        return " | ".join(
            _schema_to_typescript({**schema, "type": member})
            for member in schema_type
        )
    if schema_type == "null":
        return "null"
    if schema_type == "boolean":
        return "boolean"
    if schema_type in {"integer", "number"}:
        return "number"
    if schema_type == "string":
        return "string"
    if schema_type == "array":
        items = schema.get("items")
        item_type = (
            _schema_to_typescript(items)
            if isinstance(items, dict)
            else "unknown"
        )
        return f"Array<{item_type}>"
    if schema_type == "object" or "properties" in schema:
        properties = schema.get("properties")
        required = set(schema.get("required") or [])
        fields: list[str] = []
        if isinstance(properties, dict):
            for name, definition in properties.items():
                if not isinstance(definition, dict):
                    continue
                field_name = (
                    name
                    if re.fullmatch(r"[A-Za-z_$][A-Za-z0-9_$]*", name)
                    else json.dumps(name, ensure_ascii=False)
                )
                optional = "" if name in required else "?"
                fields.append(
                    f"{field_name}{optional}: {_schema_to_typescript(definition)}"
                )
        additional = schema.get("additionalProperties")
        if isinstance(additional, dict):
            fields.append(f"[key: string]: {_schema_to_typescript(additional)}")
        elif additional is True:
            fields.append("[key: string]: unknown")
        if not fields:
            return "Record<string, unknown>"
        return "{ " + "; ".join(fields) + " }"
    return "unknown"


if __name__ == "__main__":
    main()
