# ruff: noqa: E402,I001
import json
import re
import sys
from pathlib import Path
from typing import Any

if __package__ in {None, ""}:
    backend_root = Path(__file__).resolve().parents[1]
    if str(backend_root) not in sys.path:
        sys.path.insert(0, str(backend_root))

from main import create_app


ROOT = Path(__file__).resolve().parents[2]
OPENAPI_PATH = ROOT / "frontend" / "src" / "generated" / "openapi.json"
CONTRACT_PATH = ROOT / "frontend" / "src" / "generated" / "api-contract.ts"
HTTP_METHODS = {"get", "post", "put", "patch", "delete"}


def main() -> None:
    schema = create_app().openapi()
    OPENAPI_PATH.parent.mkdir(parents=True, exist_ok=True)
    OPENAPI_PATH.write_text(
        json.dumps(schema, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    CONTRACT_PATH.write_text(_contract_source(schema), encoding="utf-8")
    print(json.dumps({"openapi": str(OPENAPI_PATH), "contract": str(CONTRACT_PATH)}))


def _contract_source(schema: dict[str, Any]) -> str:
    operations = []
    for path, methods in sorted(schema.get("paths", {}).items()):
        if not isinstance(methods, dict):
            continue
        for method, definition in sorted(methods.items()):
            if method not in HTTP_METHODS or not isinstance(definition, dict):
                continue
            operations.append(
                {
                    "method": method.upper(),
                    "path": path,
                    "operationId": definition.get("operationId", ""),
                }
            )

    path_union = _literal_union(sorted({item["path"] for item in operations}))
    method_union = _literal_union(sorted({item["method"] for item in operations}))
    operation_union = _literal_union(
        sorted(item["operationId"] for item in operations if item["operationId"])
    )
    body = json.dumps(operations, ensure_ascii=False, indent=2)
    body = re.sub(r'"([^"]+)":', r"\1:", body)
    return (
        "/* This file is generated by backend/scripts/export_openapi.py. */\n"
        "/* eslint-disable */\n\n"
        f"export type ApiPath = {path_union};\n"
        f"export type ApiMethod = {method_union};\n"
        f"export type ApiOperationId = {operation_union};\n\n"
        f"export const apiContract = {body} as const;\n"
    )


def _literal_union(values: list[str]) -> str:
    if not values:
        return "never"
    return " | ".join(json.dumps(value, ensure_ascii=False) for value in values)


if __name__ == "__main__":
    main()
